dataset_str:
  "BlendedMVS(
    split='${dataset.blendedmvs.train.split}',
    resolution=${dataset.blendedmvs.train.dataset_resolution},
    aug_crop='${dataset.blendedmvs.train.aug_crop}',
    aug_monocular=${dataset.blendedmvs.train.aug_monocular},
    transform='${dataset.blendedmvs.train.transform}',
    data_norm_type='${dataset.blendedmvs.train.data_norm_type}',
    ROOT='${dataset.blendedmvs.train.ROOT}',
    pair_metadata_path='${dataset.blendedmvs.train.pair_metadata_path}')"
split: 'train'
dataset_resolution: ${dataset.resolution_train}
aug_crop: False
aug_monocular: 0
transform: 'imgnorm'
data_norm_type: ${model.data_norm_type}
ROOT: ${root_data_dir}/blendedmvs_processed
pair_metadata_path: ${root_data_dir}/dust3r_data_pairs/blendedmvs_pairs.npy
