train_loss:
  epe:
    class: FlowEPELoss
    kwargs:
      multiplier: 0.0
      supervision_range: occlusion
      minimum_mask_threshold: 0.1

  refinement_cross_entropy:
    class: RefinementCrossEntropyLossEfficient
    kwargs:
      multiplier: 10.0
      supervision_range: occlusion
      supervision_strategy: 4_point_average

test_loss:
  epe:
    class: FlowEPELoss
    kwargs:
      multiplier: 0.0
      supervision_range: occlusion
      minimum_mask_threshold: 0.1

  refinement_cross_entropy:
    class: RefinementCrossEntropyLoss
    kwargs:
      multiplier: 10.0
      supervision_range: occlusion
      supervision_strategy: 4_point_average
