input_embed_dim: ???
transformer_dim: ???
num_heads: ???
num_layers: ???
mlp_ratio: ???
qkv_bias: ???
qk_norm: ???
position_encoding: ???
normalize_intermediate: ???
returned_intermediate_layers: ???
decoder_kwargs: {}
decoder_checkpoint_path: null
