defaults:
  - encoder: dinov2_l
  - decoder: base_global
  - feature_head: dpt
  - adaptor_map: flow_scale_both
  - classification_feature: mlp_feature

model_class: UniFlowMatchClassificationRefinement

data_norm_type: 'dinov2'
info_sharing_and_head_structure: 'dual+single'
num_channels: 2

# for decoder
returned_intermediate_layers: [5, 8]
transformer_dim: ${model.decoder.transformer_dim}

# for classification refinement
classification_head_type: patch_mlp
classification_head_kwargs: ${model.classification_feature.kwargs}

pretrained_backbone_checkpoint_path: null

refinement_range: 7 # pixels
use_unet_feature: True
use_unet_batchnorm: True # Greatly accelerates training convergence
feature_combine_method: 'modulate'

model_args:
  # Encoder Args
  encoder_str: ${model.encoder.encoder_str}
  encoder_kwargs: ${model.encoder.encoder_kwargs}
  # Info Sharing Args
  info_sharing_str: ${model.decoder.info_sharing_type}
  info_sharing_kwargs: ${model.decoder.info_sharing_kwargs}
  # Output Head Args
  head_type: dpt
  feature_head_kwargs: ${model.feature_head}
  adaptors_kwargs: ${model.adaptor_map}
  # Classification Head Args
  classification_head_type: ${model.classification_head_type}
  classification_head_kwargs: ${model.classification_head_kwargs}
  refinement_range: ${model.refinement_range}
  use_unet_feature: ${model.use_unet_feature}
  use_unet_batchnorm: ${model.use_unet_batchnorm}
  feature_combine_method: ${model.feature_combine_method}
  # Pretrained checkpoint path
  pretrained_backbone_checkpoint_path: ${model.pretrained_backbone_checkpoint_path}
  pretrained_checkpoint_path: null
