dataset_str:
  "Spring(
    split='${dataset.spring.train.split}',
    resolution=${dataset.spring.train.dataset_resolution},
    aug_crop=${dataset.spring.train.aug_crop},
    aug_monocular=${dataset.spring.train.aug_monocular},
    transform='${dataset.spring.train.transform}',
    data_norm_type='${dataset.spring.train.data_norm_type}',
    ROOT='${dataset.spring.train.ROOT}')"
split: 'train'
dataset_resolution: ${dataset.resolution_train}
aug_crop: False
aug_monocular: 0.0 # Not implemented Yet
transform: 'imgnorm'
data_norm_type: ${model.data_norm_type}
ROOT: ${root_data_dir}/spring_processed
