
flow:
  class: FlowAdaptor
  kwargs:
    name: flow
    flow_mean: [0.0, 0.0]
    flow_std: [25, 25]
    base_shape: [224, 224]
    scale_strategy: scale_both
    output_normalized_coordinate: False

non_occluded_mask:
  class: MaskAdaptor
  kwargs:
    name: non_occluded_mask

inlier_mask:
  class: MaskAdaptor
  kwargs:
    name: inlier_mask

flow_cov:
  class: Covariance2DAdaptor
  kwargs:
    name: flow_cov
    parametrization: exp_tanh
